Feature/upgrade to nx 20
koliveira15/nx-sonarqube pull request #117
Opened 2024-10-16 06:17 UTC by gcko

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [XX] Configuration related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [X] @koliveira15/nx-sonarqube
- [ ] docs-site

## What is the current behavior?

Currently, nx-sonarqube fails when using NX 20 

Closes #116 

## What is the new behavior?

Updated the usages of `workspace` to `projectConfigurations`

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

** It should not have a breaking change **, but it does need to be tested if previous versions of NX continue to work correctly. It has been tested to work correctly with NX 20

## Other information

2024-10-22 08:34 UTC, gcko commented
hey @koliveira15 , let me know if there is anything I can do to help out with this PR - 🙏

2024-10-23 19:25 UTC, Tommy228 commented on nx.json
> +  "useLegacyCache": true
This may come from the automatic migrations, but using the new DB cache shouldn't be an issue for this project right?

2024-10-30 01:27 UTC, jaredterm commented
Hey @koliveira15 , please let me know if there is anything else needed for this PR.

As an aside, it might be worthwhile contacting NX and making this an official plugin 🤔 IMO static analysis is integral to development pipeline and I personally would push strongly for its inclusion to the NX family

2024-11-04 01:47 UTC, gcko commented
@koliveira15 Anything I can do to help? This is becoming a blocker in our repository as it precludes us from updating `nx` and associated dependencies. Please let me know how I can contribute 🙏

2024-11-04 15:22 UTC, ErickRodrCodes commented
since he is busy, I will fork it out and move it to 20. we are having the same blocker as it is critical for us to use `nx import` to speed up monorepo work on our side.

2024-11-06 14:49 UTC, ErickRodrCodes commented
It seems I am unable to create the package as I'm tied to several things at work. If there is no update in 15 days, I will retry to fork it and somehow own it.

2024-11-12 19:16 UTC, koliveira15 requested changes

2024-11-12 19:16 UTC, koliveira15 commented on migrations.json
add `migrations.json` so it's easier to track down what was automated in this upgrade

2024-11-13 01:57 UTC, gcko commented on migrations.json
@koliveira15 done, I also updated nx to the latest and bumped some of the other minor dependencies as well 🙏

2024-11-14 13:38 UTC, koliveira15 approved these changes

2024-11-14 13:38 UTC, merged