Fix coverage
koliveira15/nx-sonarqube pull request #25
Opened 2023-04-04 13:09 UTC by albthali

Allow nx-sonarqube plugin to detect [coverageDirectory](https://nx.dev/packages/jest/executors/jest#coverageDirectory) and properly add coverage files.

2023-04-11 14:28 UTC, koliveira15 requested changes

2023-04-11 14:29 UTC, koliveira15 requested changes

2023-04-11 16:24 UTC, albthali commented on packages/nx-sonarqube/src/executors/scan/utils/utils.ts
> +        if (dep.testTarget.options.coverageDirectory) {
I covered it in the e2e test.  I will add a unit test to check this case.

2023-04-12 13:39 UTC, koliveira15 approved these changes

2023-04-12 13:39 UTC, merged