Rewrite Message from @nx/devkit
koliveira15/nx-sonarqube pull request #47
Opened 2023-09-28 06:53 UTC by gcko

This PR addresses Issue #46 by rewriting the error message, removing 'ERROR', while still maintaining the necessary information

2023-09-29 08:27 UTC, gcko commented
@koliveira15 The following is failing - this isn't related with my PR:

```
ERROR: Error during SonarScanner execution
ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
ERROR: 
The SonarQube scan failed for project 'nx-sonarqube-e2e'. Error: Error: Command failed: /home/runner/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner --from=ScannerNpm/3.0.1
FAIL nx-sonarqube-e2e e2e/nx-sonarqube-e2e/tests/nx-sonarqube.spec.ts (51.991 s)
  nx-sonarqube e2e
  ```

2023-09-29 12:02 UTC, koliveira15 requested changes

2023-09-29 12:03 UTC, koliveira15 commented
> @koliveira15 The following is failing - this isn't related with my PR:
> 
> ```
> ERROR: Error during SonarScanner execution
> ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
> ERROR: 
> The SonarQube scan failed for project 'nx-sonarqube-e2e'. Error: Error: Command failed: /home/runner/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner --from=ScannerNpm/3.0.1
> FAIL nx-sonarqube-e2e e2e/nx-sonarqube-e2e/tests/nx-sonarqube.spec.ts (51.991 s)
>   nx-sonarqube e2e
> ```

Please ignore for now. e2e passes for me so I need to check whats going on with Actions and the sonar runner

2023-09-30 15:50 UTC, gcko commented on package.json
> +  "version": "1.0.1",
reverted.

2023-09-30 15:50 UTC, koliveira15 approved these changes

2023-09-30 15:50 UTC, merged